project:
  type: website
  output-dir: docs

website:
  title: "Global Health Engineering"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: slides.qmd
        text: Slides
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute: 
  freeze: auto


