project:
  type: website

website:
  title: "Global Health Engineering"
  navbar:
    left:
      - href: index.qmd
        text: Slides
      - slides.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



