project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Global Health Engineering"
  description: "Homepage for slides, tutorials, and other teaching material."
  site-url: "https://global-health-engineering.github.io/website/"
  navbar:
    tools:
      - icon: github
        href: https://github.com/Global-Health-Engineering/website
    left:
      - href: index.qmd
        text: Home
      - href: 1-slides/index.qmd
        text: Slides
      - text: Tutorials
        menu: 
          - 2-tutorials/data-package.qmd
      - href: 3-blog/index.qmd
        text: Blog
        
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-copy: true
    code-overflow: wrap

execute: 
  freeze: auto


