---
title: "dsn-agentsforsci"
format: html
---

# 2023

## Digital Research 

left:

- Git was hard
-

pull-right:

- Image of a stone age person using a tool
- OR physical bookpress
:

# Polls

## Who has send a document where AI was used?

## Who can proof which parts of the document were generated by AI and which parts by code?

## How?

- from memory?
- documented?
- automated?

# 2026

## Digital Research

- Git is now a language prompt away
- Commits can document history of changes
- Issue document history of decisions
- Your AI agent is your strongest collaborator

pull-right:

- a GIF of a terminal with a bumping Claude Code image

:

# Declaration of AI

## 

full-screen:

Taxonomy screenshot

# Declaration of human

##

left:

- Paper in 30 minutes
- (well documented) open data makes it possible (Yiiipiiiiiiieeee)
- How to prove our work?

right:

- Screenshot of LSE blog post or scientific article rtelated to it

# Git for Scientists

## Teaching the "need to know"

- list them

## OER

- QR
- Handbook for how to setup and run the workshop

## RDC 2026, Bern

- Screenshot of Workshop in Bern
- Audience: Educators interested in teaching the workshop

# Agents for Scientists

## Handing over the "need to know" to the AI

- Work safely (use git to revert)
- Expriment freely (endless possibilities with agentic AI)
- 1st 1-day workshop on 29th September

# FAIR by doing

## Expression of interest

left:

- 12-months 
- 5 workshops
- Git / GitHub / FAIR data publishing / Agentic AI
- 1-day with Greg Wilson: Organizational Change for Open Science
- Anyone is welcome, but especially qualitative researcher and people from non-IT backgrounds

right:

- QR

## Thanks [{{< fa sun >}}]{.accent} {#thanks}

::: {.columns}
::: {.column width="47%"}

::: {.kicker}
References
:::

- **These slides:** [download as PDF](https://github.com/Global-Health-Engineering/aguasan/raw/main/slides/aguasan-2027-topic-pitch-openwashdata-lschoebitz.pdf)
- **Built with Quarto and reveal.js:** [quarto.org/docs/presentations/revealjs](https://quarto.org/docs/presentations/revealjs/)


**Funding and support:** [Swiss Reproducibility Network (SwissRN)](https://www.swissrn.org/contents/community/nodes/) local node at ETH Zurich & [Data Stewardship Network at ETH Zurich](https://library.ethz.ch/en/researching-and-publishing/data-management-and-policies/research-data-management/data-stewardship.html), funded by the [swissuniversities Open Science Programme](https://www.swissuniversities.ch/en/topics/open-science/open-science-programme) & [Global Health Engineering group at ETH Zurich](https://ghe.ethz.ch/)

:::
::: {.column width="53%"}

::: {.kicker}
Resources
:::

- Git for Scientists Handbook: https://gitforsci.github.io/website
- Agents for Scientists: https://github.com/agentsforsci
- FAIR by doing proposal: https://github.com/Global-Health-Engineering/fair-training
- FAIR by doing expression of interest form: 

:::
:::

::: {.foot}
All material is licensed under Creative Commons Attribution 4.0 International (CC BY 4.0).
:::

**Slides:**



