---
title: "Reference Management"
subtitle: "with Zotero"
author: 
  - name: Lars Schöbitz
    email: lschoebitz@ethz.ch
    affiliations:
        - name: Global Health Engineering - ETH Zurich
          url: https://ghe.ethz.ch/
date: 2023-10-12
date-format: long
footer: "[{{< fa link >}} global-health-engineering.github.io/website/1-slides/](https://global-health-engineering.github.io/website/1-slides/)"
format: 
  revealjs: 
    theme: slides.scss
    transition: fade
    slide-number: true
editor: source
editor_options: 
  chunk_output_type: console
bibliography: hubris-to-hope.bib
execute:
  freeze: auto
---

```{r}
#| label: setup
#| include: false

# set width of code output
options(width = 65)

# load background packages
library(countdown)
```


## {{< fa hand >}} {.center-align auto-animate="true"}

::: {style="margin-top: 50px; font-size: 1.5em"}
Who has published a report, scientific article, or similar?
:::

## {{< fa hand >}} {.center-align auto-animate="true"}

::: {style="margin-top: 50px; font-size: 1.5em"}
Who already uses a reference management tool? (e.g. Mendeley, EndNote, Zotero)
:::

## Four terms

- Citation
- Reference
- Bibliography
- Citation Style Language

## What's a Citation?

::: {.incremental}

- Many visitors still expect a personal pick-up, despite the availability of taxi services [@tilley2021].
- In @tilley2021, the authors describe how visitors still expect a personal pick-up, despite the availability of taxi services.

::: 

::: {.notes}
**Explanation**
A citation is a reference to the source of information used in your research. Any time you directly quote, paraphrase, or summarize the essential elements of someone else's idea in your work, an in-text citation should follow. For example, in APA style, a citation might look like this: (Tilley and Kalina, 2021). 

**Analogy**
Think of a citation as a signpost on a road trip. It tells you where the information came from and points you in the direction of the full details (the destination), which can be found in the reference list.
:::

## What's a Citation?

- Many visitors still expect a personal pick-up, despite the availability of taxi services [@tilley2021]**.**
- In @tilley2021, the authors describe how visitors still expect a personal pick-up, despite the availability of taxi services.

::: {.callout-important}
## Important
The period is behind the citation.
:::

## What's a Reference?

- detailed description of the source of information
- author's name, title, year of publication, publisher, URL, DOI, etc.

::: {#refs}
:::

::: {.notes}

**Explanation**

A reference is a detailed description of the source of information that you want to give credit to via a citation. In APA style, a reference provides comprehensive details about a source, including the author's name, the title of the source, the year of publication, and the publisher or URL.

**Analogy**

A reference is like a detailed map at the end of your road trip (paper). It provides all the details about the source (destination) that the citation (signpost) pointed to.

::: 

## What's a Bibliography?

- list of references in a research paper or project
- includes all sources used, whether they were directly quoted or not
- listed alphabetically by the author's last name in the reference list

### References

::: {#refs}
:::

## What's Citation Style Language (CSL)?

- It's what your citation and generated bibliography look like
- APA Style

## Why use a reference management tool?

- It's a lot of work to manage references manually
- It's easy to make mistakes
- It's easy to lose track of references

## Why use Zotero?

- free
- open source
- cross-platform (Windows, Mac, Linux)
- collaboration in groups
- integration with word processors

## How to use Zotero with Word

- live

